### ISSUE TITLE
Problems with Variable Definitions！

### ISSUE THREAD

**Issue by junyizeng** [kristen-rang/FFCLIP#3]
Thank you very much for your open source, but I hope you will double check your open source code and improve the definition of variables such as self.age,self.emotion,self.config.lossage_lambda,self.config.emotion_lambda,self.config.clip_ lambda. The first 3 I have filled in according to my understanding based on my browsing of the code, where are the definitions of the last 3 variables and what should their values be?

Traceback (most recent call last):
  File "/root/code/FFCLIP/Coach.py", line 344, in <module>
    coach.train()
  File "/root/code/FFCLIP/Coach.py", line 152, in train
    loss, loss_dict = self.calc_loss(w.cuda(), w_hat.cuda(), img, img_hat, discirption, text)
  File "/root/code/FFCLIP/Coach.py", line 246, in calc_loss
    discirption[i].contiguous()).mean() * self.configs.loss.emotion_lambda
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key emotion_lambda
    full_key: loss.emotion_lambda
    object_type=dict

**Comment by kristen-rang** [comment]
just delete them directly~ Thx for pointing this out.
